// Generated by `node tools/generate-client.mjs` from `api/openapi.yaml`.
// Do not edit this file by hand (DX-4, I12). Run `make client` to regenerate.

/**
 * An immutable directory ID that identifies a person or a group (ID-4). A name or an email
 * address never identifies a principal.
 */
export type ActorId = string

/**
 * The client-created ID of one operation (UUIDv7).
 */
export type OperationId = string

/**
 * One change (MVP.md 3). The client creates its ID (ADR 0004).
 */
export interface Operation {
  readonly id: OperationId
  readonly type: string
  readonly at: number
  readonly actor?: ActorId
  readonly payload: Record<string, unknown>
}

/**
 * An immutable, ordered record of an occurrence. The single writer assigns `seq` (ADR 0004).
 */
export interface Event {
  readonly seq: number
  readonly operationId: OperationId
  readonly type: string
  readonly at: number
  readonly actor?: ActorId
  readonly payload: Record<string, unknown>
}

/**
 * The single sequence of all events, in one global order.
 */
export type Log = readonly Event[]

/**
 * The derived state, rebuilt from the log (I4).
 */
export interface State {
  readonly applied: readonly OperationId[]
  readonly log: Log
}

export interface ClientConfig {
  readonly baseUrl: string
  readonly token: string
}

let config: ClientConfig | undefined

export function setClient(next: ClientConfig): void {
  config = next
}

function configured(): ClientConfig {
  if (config === undefined) throw new Error('the client is not configured; call setClient')
  return config
}

function headers(): Record<string, string> {
  return { authorization: `Bearer ${configured().token}` }
}

export async function appendOperation(operation: Operation): Promise<Event> {
  const response = await fetch(`${configured().baseUrl}/api/v1/operations`, {
    method: 'POST',
    headers: { ...headers(), 'content-type': 'application/json' },
    body: JSON.stringify(operation),
  })
  if (!response.ok) throw new Error(`request failed: ${response.status} ${response.statusText}`)
  return (await response.json()) as Event
}

export async function readLog(): Promise<Log> {
  const response = await fetch(`${configured().baseUrl}/api/v1/log`, {
    method: 'GET',
    headers: headers(),
  })
  if (!response.ok) throw new Error(`request failed: ${response.status} ${response.statusText}`)
  return (await response.json()) as Log
}

export async function readState(): Promise<State> {
  const response = await fetch(`${configured().baseUrl}/api/v1/state`, {
    method: 'GET',
    headers: headers(),
  })
  if (!response.ok) throw new Error(`request failed: ${response.status} ${response.statusText}`)
  return (await response.json()) as State
}
