#!/usr/bin/env node
// Issue #93, DX-4, I12, MVP.md 9.1: the interface uses only the generated API
// client, and the client is generated from the OpenAPI document. This
// generator reads api/openapi.yaml and writes interface/client/client.ts: one
// type per schema and one function per operation, with the base URL and the
// bearer token injected through `setClient`. The output is deterministic, so
// the generator reproduces the checked-in client byte for byte;
// tools/client.test.ts fails on drift.
//
// Usage: node tools/generate-client.mjs [outFile]
// The output path defaults to <repo>/interface/client/client.ts.

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { parse } from 'yaml'

const repo = join(fileURLToPath(new URL('.', import.meta.url)), '..')
const document = parse(readFileSync(join(repo, 'api', 'openapi.yaml'), 'utf8'))
const out = process.argv[2] ?? join(repo, 'interface', 'client', 'client.ts')

const schemas = document.components.schemas

// The fixed preamble. The generated client is a checked-in artifact, so the
// header names the generator and the make target that reruns it.
const HEADER = [
  '// Generated by `node tools/generate-client.mjs` from `api/openapi.yaml`.',
  '// Do not edit this file by hand (DX-4, I12). Run `make client` to regenerate.',
].join('\n')

// One `export` per schema of the document, in document order. An object schema
// with properties becomes an interface; every other schema becomes a type.
function typeSection(schemas) {
  return Object.keys(schemas)
    .map((name) => {
      const schema = schemas[name]
      const doc = schema.description ? `${docComment(schema.description)}\n` : ''
      return `${doc}${declaration(name, schema)}`
    })
    .join('\n\n')
}

function declaration(name, schema) {
  if (schema.type === 'object' && schema.properties !== undefined) {
    const required = new Set(schema.required ?? [])
    const fields = Object.keys(schema.properties).map((key) => {
      const optional = required.has(key) ? '' : '?'
      return `  readonly ${key}${optional}: ${typeOf(schema.properties[key])}`
    })
    return [`export interface ${name} {`, ...fields, '}'].join('\n')
  }
  return `export type ${name} = ${typeOf(schema)}`
}

// The TypeScript type of a schema or a property schema. A reference becomes
// the referenced type, an array becomes a readonly array, and an object
// without properties becomes a JSON record.
function typeOf(schema) {
  if (schema.$ref !== undefined) return refName(schema.$ref)
  switch (schema.type) {
    case 'string':
      return 'string'
    case 'number':
    case 'integer':
      return 'number'
    case 'boolean':
      return 'boolean'
    case 'array':
      return `readonly ${typeOf(schema.items)}[]`
    default:
      return 'Record<string, unknown>'
  }
}

// The configuration surface and the two helpers that the operations share.
// The base URL and the token are injected once, so the operation functions
// keep the signature of the OpenAPI operation.
function clientSection() {
  return [
    'export interface ClientConfig {',
    '  readonly baseUrl: string',
    '  readonly token: string',
    '}',
    '',
    'let config: ClientConfig | undefined',
    '',
    'export function setClient(next: ClientConfig): void {',
    '  config = next',
    '}',
    '',
    'function configured(): ClientConfig {',
    "  if (config === undefined) throw new Error('the client is not configured; call setClient')",
    '  return config',
    '}',
    '',
    'function headers(): Record<string, string> {',
    // biome-ignore lint/suspicious/noTemplateCurlyInString: this text is emitted into the generated client.
    '  return { authorization: `Bearer ${configured().token}` }',
    '}',
  ].join('\n')
}

// One function per operation: the method and the path come from the document,
// the request parameter and the return type come from the schemas.
function renderOperation({ path, method, operation }) {
  const request = operation.requestBody?.content?.['application/json']?.schema
  const parameter = request === undefined ? undefined : lowerFirst(refName(request.$ref))
  const parameterType = request === undefined ? undefined : refName(request.$ref)
  const success = Object.entries(operation.responses).find(([status]) => /^2\d\d$/.test(status))
  const returnType = refName(success[1].content['application/json'].schema.$ref)

  const args = parameter === undefined ? '' : `${parameter}: ${parameterType}`
  const init = [`    method: '${method}',`]
  if (parameter === undefined) init.push('    headers: headers(),')
  else {
    init.push("    headers: { ...headers(), 'content-type': 'application/json' },")
    init.push(`    body: JSON.stringify(${parameter}),`)
  }

  return [
    `export async function ${operation.operationId}(${args}): Promise<${returnType}> {`,
    `  const response = await fetch(\`\${configured().baseUrl}${path}\`, {`,
    ...init,
    '  })',
    // biome-ignore lint/suspicious/noTemplateCurlyInString: this text is emitted into the generated client.
    '  if (!response.ok) throw new Error(`request failed: ${response.status} ${response.statusText}`)',
    `  return (await response.json()) as ${returnType}`,
    '}',
  ].join('\n')
}

// Every operation of the document, ordered by operationId so the output does
// not depend on the order of the paths.
function operationsOf(document) {
  const found = []
  for (const [path, methods] of Object.entries(document.paths)) {
    for (const [method, operation] of Object.entries(methods)) {
      if (method === 'parameters') continue
      found.push({ path, method: method.toUpperCase(), operation })
    }
  }
  return found.sort((left, right) =>
    left.operation.operationId.localeCompare(right.operation.operationId)
  )
}

function refName(ref) {
  const prefix = '#/components/schemas/'
  if (!ref.startsWith(prefix)) throw new Error(`unsupported reference: ${ref}`)
  return ref.slice(prefix.length)
}

function lowerFirst(name) {
  return name.charAt(0).toLowerCase() + name.slice(1)
}

// A schema description as a JSDoc comment, wrapped to the line width of the
// repository so the output matches the formatter.
function docComment(text) {
  const words = String(text).replace(/\s+/g, ' ').trim().split(' ')
  const lines = ['/**']
  let line = ''
  for (const word of words) {
    if (line === '') line = word
    else if (` * ${line} ${word}`.length > 96) {
      lines.push(` * ${line}`)
      line = word
    } else line = `${line} ${word}`
  }
  if (line !== '') lines.push(` * ${line}`)
  lines.push(' */')
  return lines.join('\n')
}

const operations = operationsOf(document)
const sections = [HEADER, typeSection(schemas), clientSection(), ...operations.map(renderOperation)]
mkdirSync(dirname(out), { recursive: true })
writeFileSync(out, `${sections.join('\n\n')}\n`)
console.log(
  `client: wrote ${out} from ${Object.keys(schemas).length} schemas and ${operations.length} operations`
)
